name: Keep Website Alive

on:
  schedule:
    # Run every 5 minutes between 5am and 11:59pm UTC (10:30am to 5:29am IST)
    - cron: '*/5 5-23 * * *'
    # Run every 10 minutes between 12am and 4:55am UTC (5:30am to 10:25am IST)
    - cron: '*/10 0-4 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Show current time and timezone
      run: |
        echo "Current time: $(date)"
        echo "Current timezone: $(date +%Z) $(date +%z)"
        echo "UTC time: $(date -u)"
    
    - name: Ping website
      run: |
        echo "Starting website ping at $(date)"
        echo "Workflow run ID: ${{ github.run_id }}"
        echo "Workflow run number: ${{ github.run_number }}"
        python scraper.py
      continue-on-error: true
      
    - name: Show completion
      if: always()
      run: |
        echo "Ping session completed at $(date)"
